openApp()
electrikmilk/cherri pull request #1
Opened 2022-11-02 00:43 UTC by JosephShenton

Implemented openApp()

iOS 16/15(?) uses `WFSelectedApp` over `WFAppIdentifier`

2022-11-02 05:09 UTC, electrikmilk requested changes

2022-11-02 05:09 UTC, electrikmilk commented on actions_std.go
> +				noMax:     true,
Infinite arguments don't apply for this action, please remove this field.

I may make changes to make that field more clear.

2022-11-02 05:09 UTC, electrikmilk commented on actions_std.go
> +				argumentValue("WFSelectedApp", args, 0), // WFAppIdentifier Previously - changed in iOS 15(?)
`WFAppIdentifier` belongs here instead.

`WFSelectedApp` is a dictionary with a `BundleIdentifier` with the same value as `WFAppIdentifier`.

```go
{
	key:      "WFSelectedApp",
	dataType: Dictionary,
	value: []plistData{
		argumentValue("BundleIdentifier", args, 0),
	},
},
```

Please remove the comment.

[Please confirm action parameters with testing before submitting a PR.](https://github.com/electrikmilk/cherri/blob/main/CONTRIBUTING.md)

2022-11-02 05:09 UTC, electrikmilk commented on actions_std.go
> +		identifier: "openapp",
If the action key (e.g. `actions["key"]`) and the `identifier` are the same, the identifier field can be removed.

2022-11-02 05:10 UTC, electrikmilk commented
Thanks for making the first contribution!

2022-11-02 05:45 UTC, JosephShenton commented
Amazing, fixing these up now!

2022-11-02 06:11 UTC, JosephShenton commented
Hey! They should be fixed. I've tried squashing the commits, but I am unsure as to if that succeeded. Please let me know if it didn't.

2022-11-02 14:32 UTC, electrikmilk commented on actions_std.go
> +				name:      "bundleID",
Let's name this parameter `appID` instead.

2022-11-02 14:47 UTC, electrikmilk commented
> Hey! They should be fixed. I've tried squashing the commits, but I am unsure as to if that succeeded. Please let me know if it didn't.

The action itself looks great! But, the 7 commits should be squashed into 1 commit.

Please try the following
```
git reset --soft HEAD~1
git push --force
```

2022-11-04 11:05 UTC, JosephShenton commented
Hey! Yup! I can do that!

2022-11-05 10:45 UTC, JosephShenton commented
Hey! It should be fixed now!

2022-11-05 16:40 UTC, electrikmilk commented
> Hey! It should be fixed now!

Thanks for your contribution!

2022-11-05 16:40 UTC, merged